#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AutoReStory.Resource", IsApplication=true)]

namespace AutoReStory
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040002
			public const int activity_horizontal_margin = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int activity_vertical_margin = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int nav_header_height = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int nav_header_vertical_spacing = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_shape = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cell_shape = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int delete = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int gradient_bg = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gradient_bg_alternate = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int gradient_bg_hover = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int gradient_bg_hover_alternate = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int input_shape = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int list_selector = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int list_selector_alternate = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int splash_logo = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int addEdit_AutoId = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int addEdit_Color = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int addEdit_Description = 2131165193;
			
			// aapt resource value: 0x7f070022
			public const int addEdit_Location = 2131165218;
			
			// aapt resource value: 0x7f070006
			public const int addEdit_Make = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int addEdit_Model = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int addEdit_Year = 2131165189;
			
			// aapt resource value: 0x7f07001f
			public const int addEdit_btnSave = 2131165215;
			
			// aapt resource value: 0x7f07002d
			public const int autoList_btnAdd = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int autoList_btnSearch = 2131165228;
			
			// aapt resource value: 0x7f07002e
			public const int autoList_listView = 2131165230;
			
			// aapt resource value: 0x7f07002b
			public const int autoList_txtSearch = 2131165227;
			
			// aapt resource value: 0x7f07000d
			public const int body = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int bodyBar = 2131165198;
			
			// aapt resource value: 0x7f070023
			public const int datePicker1 = 2131165219;
			
			// aapt resource value: 0x7f070017
			public const int electrical = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int electricalBar = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int frame = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int frameBar = 2131165210;
			
			// aapt resource value: 0x7f07000f
			public const int glass = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int glassBar = 2131165200;
			
			// aapt resource value: 0x7f070003
			public const int imageView1 = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070028
			public const int lr_color = 2131165224;
			
			// aapt resource value: 0x7f07002a
			public const int lr_deleteBtn = 2131165226;
			
			// aapt resource value: 0x7f070029
			public const int lr_description = 2131165225;
			
			// aapt resource value: 0x7f070026
			public const int lr_make = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int lr_model = 2131165223;
			
			// aapt resource value: 0x7f070025
			public const int lr_year = 2131165221;
			
			// aapt resource value: 0x7f070015
			public const int mechanical = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int mechanicalBar = 2131165206;
			
			// aapt resource value: 0x7f070002
			public const int openCamera = 2131165186;
			
			// aapt resource value: 0x7f07001d
			public const int overall = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int overallBar = 2131165214;
			
			// aapt resource value: 0x7f07000b
			public const int paint = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int paintBar = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int space1 = 2131165194;
			
			// aapt resource value: 0x7f070021
			public const int spinner1 = 2131165217;
			
			// aapt resource value: 0x7f070030
			public const int start = 2131165232;
			
			// aapt resource value: 0x7f070000
			public const int tableLayout = 2131165184;
			
			// aapt resource value: 0x7f070020
			public const int tableLayout1 = 2131165216;
			
			// aapt resource value: 0x7f070024
			public const int task_btnAdd = 2131165220;
			
			// aapt resource value: 0x7f07002f
			public const int textView1 = 2131165231;
			
			// aapt resource value: 0x7f070031
			public const int textView2 = 2131165233;
			
			// aapt resource value: 0x7f07001b
			public const int tires = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int tiresBar = 2131165212;
			
			// aapt resource value: 0x7f070011
			public const int trim = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int trimBar = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int upholstery = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int upholsteryBar = 2131165204;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddEditAutos = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddEditTask = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int list_row_auto_list = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Setup = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int button_style = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int input_style = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
